### ISSUE TITLE
java.lang.IllegalStateException: Missing values for keyframe.

### ISSUE THREAD

**Issue by imbudhiraja** [react-native-community/lottie-react-native#473]
### Description

java.lang.IllegalStateException: Missing values for keyframe.
        at com.airbnb.lottie.animation.keyframe.FloatKeyframeAnimation.getValue(FloatKeyframeAnimation.java:16)
        at com.airbnb.lottie.animation.keyframe.FloatKeyframeAnimation.getValue(FloatKeyframeAnimation.java:8)
        at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.getValue(BaseKeyframeAnimation.java:125)
        at com.airbnb.lottie.utils.Utils.applyTrimPathIfNeeded(Utils.java:71)
        at com.airbnb.lottie.animation.content.ShapeContent.getPath(ShapeContent.java:64)
        at com.airbnb.lottie.animation.content.BaseStrokeContent.draw(BaseStrokeContent.java:164)
        at com.airbnb.lottie.animation.content.StrokeContent.draw(StrokeContent.java:41)
        at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:161)
        at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:161)
        at com.airbnb.lottie.model.layer.ShapeLayer.drawLayer(ShapeLayer.java:30)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:201)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:100)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:201)
        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:319)
        at android.widget.ImageView.onDraw(ImageView.java:1360)
        at android.view.View.draw(View.java:20207)
        at android.view.View.buildDrawingCacheImpl(View.java:19478)
        at android.view.View.buildDrawingCache(View.java:19338)
        at android.view.View.draw(View.java:19927)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:684)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at com.facebook.react.ReactRootView.dispatchDraw(ReactRootView.java:225)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20210)
        at com.android.internal.policy.DecorView.draw(DecorView.java:780)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3311)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3115)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2484)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
2019-04-25 11:24:57.977 9253-9253/com.mobile.jambo E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Expected behavior:** [What you expected to happen]
It should render the animation

**Actual behavior:** [What actually happened]
Application breaks down with above error.

### Versions
RN - 0.59.4
lottie - 2.6.0

**NOTE:** Same JSON working  on iOS application

**Comment by u0x01** [comment]
same issue, and same json on ios working fine.

**Comment by emilioicai** [comment]
This issue should be raised in lottie-android in my opinion

**Comment by evanjmg** [comment]
It already has been raised and fixed but it's subdependency is not updated -> https://github.com/airbnb/lottie-android/issues/1177

**Comment by janet-rivas** [comment]
I have the same issue, 
Versions -
"react": "^16.8.6",
"react-native": "^0.59.4",
"lottie-react-native": "2.5.10",
--------------------------------
even when I solved some of the  dependences in node_modules/lottie-react-native/src/android/build.gradle

compileSdkVersion safeExtGet('compileSdkVersion', 28)
  buildToolsVersion safeExtGet('buildToolsVersion', '28.0.3')
  publishNonDefault true

  defaultConfig {
    minSdkVersion safeExtGet('minSdkVersion', 19)
    targetSdkVersion safeExtGet('targetSdkVersion', 28)
  }

dependencies {
  compileOnly "com.facebook.react:react-native:+"
  implementation 'com.airbnb.android:lottie:2.5.5'
  implementation 'com.android.support:appcompat-v7:28.0.0'
}
I made the app running and then I got a FATAL EXCEPTION: main
    
    java.lang.IllegalStateException: Missing values for keyframe.
        at com.airbnb.lottie.animation.keyframe.ScaleKeyframeAnimation.getValue

**Comment by mohamed-azikiou** [comment]
You are using a json lottie new format file witch is not supported before version 3.0.0
See here https://github.com/airbnb/lottie-android/issues/1177#issuecomment-495879540

**Comment by mohamed-azikiou** [comment]
You are using a json lottie new format file which is not supported before version 3.0.0
See here https://github.com/airbnb/lottie-android/issues/1177#issuecomment-495879540

**Comment by lucienbl** [comment]
Hey! 👋 I have the same issue, has this been fixed by any commit in `lottie-react-native` ?

**Comment by mohamed-azikiou** [comment]
> Hey! 👋 I have the same issue, has this been fixed by any commit in `lottie-react-native` ?

Did you set the build action to Android Asset?

**Comment by lucienbl** [comment]
> > Hey! 👋 I have the same issue, has this been fixed by any commit in `lottie-react-native` ?
> 
> Did you set the build action to Android Asset?

I just linked with `react-native link` as it's specified in the README, how can I set the build action ?

**Comment by avinashlng1080** [comment]
Can you please tell us the solution ?

**Comment by OriginLive** [comment]
Has anyone fixed this issue?

**Comment by maxired** [comment]
Should be fixed by lottie-react-native@3.1.0

**Comment by imbudhiraja** [comment]
@maxired yes its fixed for lottie-react-native@3.1.0 but issue still exists on lottie-react-native@2.6.0

**Comment by erronblackk** [comment]
this solution solve my problem 
  implementation "com.airbnb.android:lottie:3.0.3"

**Comment by geekazoid-at** [comment]
> So basically I'm screwed using animations from e.g. lottiefiles?
> 
> We're on RN 59. I was not successful getting 3.1.0 to run with jetifier in reverse mode etc. The README also recommends lower versions for RN 59 than what I would need.
> 
> Is there any way I can convert a newer bodymovin format to an older one? I could not find enough information to write a converter myself.
> 
> Could I do it with two installations of AE???
> 
> * one with a newer plugin to import it
> * save it to another format
> * import in an installation with a lower version
> * export as legacy
> 
> Any help is greatly appreciated, not sure if I can convince my client to do an RN upgrade. As a AE noob who needs to use external resources, RN59 and lottie does not seem like a very good fit. (Please) show me that I'm wrong.

Nevermind, I managed to convert to legacy. The plugin has an option to save as the old format.
