### ISSUE TITLE
CONTRIBUTING.md needs Android and iOS setup instructions

### ISSUE THREAD

**Issue by SalvatoreT** [react-native-community/lottie-react-native#650]
### Description

I want to help upgrade the dependencies, but I can't get the example code running. There's no instructions on [CONTRIBUTING.md](https://github.com/react-native-community/lottie-react-native/blob/master/CONTRIBUTING.md), but there are sections for it.

**Comment by emilioicai** [comment]
Fixed as per your PR

**Comment by SalvatoreT** [comment]
We're still missing iOS instructions, and I'm not as good in that department. 🙁
